---
# tasks file for kibana
  - name: Download and install the public signing key
    command: "rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    
  - name: add kibana repo
    copy:
      src: kibana.repo
      dest: /etc/yum.repos.d
      owner: root
      group: root
      mode: 0644

  - name: install kibana
    package: name=kibana state=present

  - name: kibana port
    lineinfile:
      path: /etc/kibana/kibana.yml
      regexp: '^#server.port'
      line: 'server.port: 5601'
      state: present
      backrefs: yes

  - name: localhost
    lineinfile:
       path: /etc/kibana/kibana.yml
       regexp: '^#server.host: "localhost"'
       line: 'server.host: "localhost"'
       state: present
       backrefs: yes

  - name: elastic serach url- set the internal IP of elastic search
    lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#elasticsearch.url'
        line: 'elasticsearch.url: "http://{{ elasticsearch_internal_ip }}:9200" '
        state: present
        backrefs: yes

  - name: start kibana
    systemd:
        name: kibana
        state: started
        daemon_reload: yes
  
  - name: enable kibana on boot
    command: sudo /bin/systemctl enable kibana.service

  - name: install EPEL repository
    package: name=epel-release state=latest


  - name: Install nginx
    package: name=nginx state=latest


  - name: copy nginx configuration file
    template:
      src: default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    notify: restart nginx


  - name: install httpd-tools
    package: name=httpd-tools state=present

  - name: start nginx on boot
    service:
      name: nginx
      enabled: yes

